require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - ./spec/**/*

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/LetSetup:
  Enabled: false

Style/Documentation:
  Enabled: false