require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - ./spec/**/*

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

RSpec/LetSetup:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 5
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
